### ISSUE TITLE
add inventory command

### ISSUE THREAD

**Issue by saltydk** [saltyorg/sb#11]
Add some type of command that just opens the inventory file with nano for easy access.

**Comment by bonny1992** [comment]
Might be cool to add a config variable (maybe in `adv_settings.yml`?) to customize the editor according to the user's preferences.

**Comment by owine** [comment]
Should just use $EDITOR

**Comment by saltydk** [comment]
Sourced from where? It isn't set in my session by default at least.

**Comment by owine** [comment]
> Sourced from where? It isn't set in my session by default at least.

The shell task sets it as nano

**Comment by saltydk** [comment]
We cannot use anything user based as it needs to work before preinstall.

**Comment by saltydk** [comment]
I can do something like
```bash
edit-inventory () {
    ${EDITOR:-nano} "/srv/git/saltbox/inventories/host_vars/localhost.yml"
}
```
However, this script runs as root so it is not aware of the user ENV.
